### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by freeart** [kittycatto/EeePC-SSD-mod#1]
Hey! Nice resource! 
After deciding to desolder pins, what are the next steps? Unfortunately, there are no photos of the motherboard to guide me. E.g I have a this 
![IMG_5172](https://github.com/kittycatto/EeePC-SSD-mod/assets/261560/bf4e5183-3494-4909-816d-5534508a6ed3)
I am a software engineer with some ability in soldering.
Could you please provide more information on how you mounted that on the Asus Eee PC motherboard?

**Comment by kittycatto** [comment]
Hello and thank you for your interest in this project!

Here is official schematics:
![image](https://github.com/kittycatto/EeePC-SSD-mod/assets/53112501/66219d1d-5ae3-42c3-8503-b72bf1e414ff)

Here is how i connected it:
![image](https://github.com/kittycatto/EeePC-SSD-mod/assets/53112501/4e6703ab-4771-45e7-bbc4-75d628c1d6eb)

Final result:
![image](https://github.com/kittycatto/EeePC-SSD-mod/assets/53112501/512b7ede-f0b1-4319-b931-4d54064d3bba)

**Comment by freeart** [comment]
Thank you so much! Looks very clean and professionally done
